name: ${project.name}
description: ${project.description}
author: AlbireoX
version: ${version.number}

main: net.voxton.mafiacraft.MafiacraftPlugin
depend: [Vault]

commands:
  mafia:
    description: Mafia base command
    usage: /mafia <tool>
  police:
    description: Police base command
    usage: /police <tool>
  city:
    description: City base command
    usage: /city <tool>
  district:
    description: District base command
    usage: /district <tool>
  section:
    description: Section base command
    usage: /section <tool>
  chat:
    description: Chat command
    usage: /chat [type]
  cworld:
    description: CWorld command
    usage: /cworld <tool>
  regime:
    description: Regime command
    usage: /regime <tool>
  squad:
    description: Squad command
    usage: /squad <tool>
  mafiacraft:
    description: Mafiacraft command
    usage: /mafiacraft <tool>
    
permissions:
  mafiacraft.admin:
    description: Allows a player to do any command and override anything.
    default: op
    children:
      mafiacraft.mod: true
    
  mafiacraft.mod:
    description: Allows a player to do moderator-related commands.
    children:
      mafiacraft.citizen: true
    
  mafiacraft.citizen:
    description: Allows the player to use all essential commands.
    children:
      mafiacraft.visitor: true
      
  mafiacraft.visitor:
    description: Allows the player to use the most basic of commands.