name: Mafiacraft
description: A mafia server plugin.
author: AlbireoX
authors: [Camaroow]
version: 0.1

main: com.crimsonrpg.mafiacraft.MafiacraftPlugin

commands:
  mafia:
    description: Mafia base command
    usage: /mafia <tool>
  police:
    description: Police base command
    usage: /police <tool>
  city:
    description: City base command
    usage: /city <tool>
  district:
    description: District base command
    usage: /district <tool>
    
permissions:
  mafiacraft.admin:
    description: Allows an admin to do many things.