name: Mafiacraft
description: A mafia server plugin.
author: AlbireoX
authors: [Camaroow]
version: 0.1

main: com.crimsonrpg.mafiacraft.MafiacraftPlugin

commands:
  mafia:
    description: Mafia base command
    usage: /mafia <tool>
  police:
    description: Police base command
    usage: /police <tool>
  city:
    description: City base command
    usage: /city <tool>
  district:
    description: District base command
    usage: /district <tool>
  section:
    description: Section base command
    usage: /section <tool>
  chat:
    description: Chat command
    usage: /chat [type]
    
permissions:
  mafiacraft.admin:
    description: Allows a player to do any command and override anything.
    default: op
    children:
      mafiacraft.mod: true
    
  mafiacraft.mod:
    description: Allows a player to do moderator-related commands.
    children:
      mafiacraft.mod.district: true
    
  mafiacraft.mod.district:
    description: Allows a player to moderate a district.
    
  mafiacraft.mod.district.desc:
    description: Allows the player to change the description of a district.